=== Thailon752/MC322/Taxi4/app/data/database.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Root element -->
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabbies" type="CabbiesType"/>
                <xs:element name="passengers" type="PassengersType"/>
                <xs:element name="paymentMethods" type="RidePaymentType"/>
                <xs:element name="rides" type="RidesType"/>
                <xs:element name="vehicles" type="VehiclesType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Cabbies section -->
    <xs:complexType name="CabbiesType">
        <xs:sequence>
            <xs:element name="cabbie" type="CabbieType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CabbieType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="cabbieId" type="xs:string"/>
            <xs:element name="rating" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="licenseNumber" type="xs:string"/>
            <xs:element name="status" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Passengers section -->
    <xs:complexType name="PassengersType">
        <xs:sequence>
            <xs:element name="passenger" type="PassengerType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PassengerType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="passengerId" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            
        </xs:sequence>
    </xs:complexType>

    <!-- Ride Payment section -->
    <xs:complexType name="RidePaymentType">
        <xs:sequence>
            <xs:element name="ridePayment" type="RidePaymentDetailsType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RidePaymentDetailsType">
        <xs:sequence>
            <xs:element name="paymentId" type="xs:string"/>
            <xs:element name="rideId" type="xs:string"/>
            <xs:element name="rideDistance" type="xs:decimal"/>
            <xs:element name="amount" type="xs:decimal"/>
            <xs:element name="rideStartTime" type="xs:dateTime"/>
            <xs:element name="paymentMethod" type="xs:string"/>
            
            
        </xs:sequence>
    </xs:complexType>

    <!-- Rides section -->
    <xs:complexType name="RidesType">
        <xs:sequence>
            <xs:element name="ride" type="RideType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RideType">
        <xs:sequence>
            <xs:element name="rideId" type="xs:string"/>
            <xs:element name="passengerId" type="xs:string"/>
            <xs:element name="cabbieId" type="xs:string"/>
            <xs:element name="vehicleId" type="xs:string"/>
            <xs:element name="pickupLocation" type="xs:string"/>
            <xs:element name="dropLocation" type="xs:string"/>
            <xs:element name="rideDistance" type="xs:decimal"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="startTime" type="xs:dateTime"/>
            
            
            
        </xs:sequence>
    </xs:complexType>

    <!-- Vehicles section -->
    <xs:complexType name="VehiclesType">
        <xs:sequence>
            <xs:element name="vehicle" type="VehicleType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VehicleType">
        <xs:sequence>
            <xs:element name="vehicleId" type="xs:string"/>
            <xs:element name="registrationNumber" type="xs:string"/>
            <xs:element name="cabbieId" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="year" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Thailon752/MC322/Tarefa 5/Tarefa05/app/data/database.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="app/data/database.xsd">
    <cabbies>
        <cabbie>
            <name>Martina</name>
            <cabbieId>95faf849-c28b-4c8f-af0a-1179f70e5504</cabbieId>
            <rating>2.375</rating>
            <phone>+55 47 94567-8901</phone>
            <email>isabela.ferreira@email.com</email>
            <licenseNumber>StUvWxYz</licenseNumber>
            <status>false</status>
        </cabbie>
    </cabbies>
    <passengers>
        <passenger>
            <name>Estevão</name>
            <passengerId>ed952f8c-f8f6-4cea-99f3-da0df48e0915</passengerId>
            <phone>+55 13 91234-5678</phone>
            <email>tiago.silva@email.com</email>
        </passenger>
    </passengers>
    <ridePayments>
        <ridePayment>
            <paymentId>bd2d9fbb-6870-4cb7-87d6-b7785c7d0387</paymentId>
            <rideId>b071038e-a51a-416c-8c1d-9e2b7cb8e638</rideId>
            <rideDistance>8.06</rideDistance>
            <amount>25.6</amount>
            <rideStartTime>2024-10-13T15:46:15.415329100</rideStartTime>
            <paymentMethod>CARTÃODECRÉDITO</paymentMethod>
        </ridePayment>
        <ridePayment>
            <paymentId>a352c4bc-50e3-4311-bc2c-42662c819e53</paymentId>
            <rideId>716565f1-9333-4883-a10b-411841d072ed</rideId>
            <rideDistance>15.29</rideDistance>
            <amount>64.8</amount>
            <rideStartTime>2024-10-13T15:46:18.000411700</rideStartTime>
            <paymentMethod>PIX</paymentMethod>
        </ridePayment>
    </ridePayments>
    <rides>
        <ride>
            <rideId>b071038e-a51a-416c-8c1d-9e2b7cb8e638</rideId>
            <passengerId>ed952f8c-f8f6-4cea-99f3-da0df48e0915</passengerId>
            <cabbieId>95faf849-c28b-4c8f-af0a-1179f70e5504</cabbieId>
            <vehicleId>6ef81f2a-53e8-48f0-bfec-eef327d05b75</vehicleId>
            <pickupLocation>SHOPPING</pickupLocation>
            <dropLocation>ESTACAODETREM</dropLocation>
            <rideDistance>8.06</rideDistance>
            <status>finalizada</status>
            <startTime>2024-10-13T15:46:15.415329100</startTime>
        </ride>
        <ride>
            <rideId>b071038e-a51a-416c-8c1d-9e2b7cb8e638</rideId>
            <passengerId>ed952f8c-f8f6-4cea-99f3-da0df48e0915</passengerId>
            <cabbieId>95faf849-c28b-4c8f-af0a-1179f70e5504</cabbieId>
            <vehicleId>6ef81f2a-53e8-48f0-bfec-eef327d05b75</vehicleId>
            <pickupLocation>SHOPPING</pickupLocation>
            <dropLocation>ESTACAODETREM</dropLocation>
            <rideDistance>8.06</rideDistance>
            <status>finalizada</status>
            <startTime>2024-10-13T15:46:15.415329100</startTime>
        </ride>
        <ride>
            <rideId>716565f1-9333-4883-a10b-411841d072ed</rideId>
            <passengerId>ed952f8c-f8f6-4cea-99f3-da0df48e0915</passengerId>
            <cabbieId>95faf849-c28b-4c8f-af0a-1179f70e5504</cabbieId>
            <vehicleId>6ef81f2a-53e8-48f0-bfec-eef327d05b75</vehicleId>
            <pickupLocation>PARQUE</pickupLocation>
            <dropLocation>BIBLIOTECA</dropLocation>
            <rideDistance>15.29</rideDistance>
            <status>em corrida</status>
            <startTime>2024-10-13T15:46:18.000411700</startTime>
        </ride>
    </rides>
    <vehicles>
        <vehicle>
            <vehicleId>6ef81f2a-53e8-48f0-bfec-eef327d05b75</vehicleId>
            <registrationNumber>ABD123</registrationNumber>
            <cabbieId>95faf849-c28b-4c8f-af0a-1179f70e5504</cabbieId>
            <model>Volkswagen</model>
            <year>2015</year>
        </vehicle>
    </vehicles>
</database>

=== Thailon752/MC322/Taxi4/app/data/database.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="app/data/database.xsd">
    <cabbies>
        <cabbie>
            <name>Martina</name>
            <cabbieId>3bfbdfac-a916-4611-befd-51384e9e9c1b</cabbieId>
            <rating>3.25</rating>
            <phone>+55 85 93456-7890</phone>
            <email>felipe.oliveira@email.com</email>
            <licenseNumber>L6mNopQr</licenseNumber>
            <status>false</status>
        </cabbie>
    </cabbies>
    <passengers>
        <passenger>
            <name>Estevão</name>
            <passengerId>f4a69956-2775-4456-bf33-4656079f83ee</passengerId>
            <phone>+55 27 92345-6789</phone>
            <email>sofia.almeida@email.com</email>
        </passenger>
    </passengers>
    <ridePayments>
        <ridePayment>
            <paymentId>7d4a9cc8-f16d-45b0-8ccb-43c24682fe29</paymentId>
            <rideId>d1307759-906e-4509-9372-dbcda00eb26b</rideId>
            <rideDistance>8.06</rideDistance>
            <amount>30.93</amount>
            <rideStartTime>2024-10-07T21:07:08.240062500</rideStartTime>
            <paymentMethod>CARTÃODECRÉDITO</paymentMethod>
        </ridePayment>
        <ridePayment>
            <paymentId>8dcdc763-9740-4d07-9557-37061dc5945b</paymentId>
            <rideId>b509a47d-867e-4b84-b3bc-bf08da2a6583</rideId>
            <rideDistance>15.29</rideDistance>
            <amount>73.53</amount>
            <rideStartTime>2024-10-07T21:07:10.240483700</rideStartTime>
            <paymentMethod>PIX</paymentMethod>
        </ridePayment>
    </ridePayments>
    <rides>
        <ride>
            <rideId>d1307759-906e-4509-9372-dbcda00eb26b</rideId>
            <passengerId>f4a69956-2775-4456-bf33-4656079f83ee</passengerId>
            <cabbieId>3bfbdfac-a916-4611-befd-51384e9e9c1b</cabbieId>
            <vehicleId>2abefd0c-35c8-4b7b-adaf-50030280d5d2</vehicleId>
            <pickupLocation>SHOPPING</pickupLocation>
            <dropLocation>ESTAÇÃODETREM</dropLocation>
            <rideDistance>8.06</rideDistance>
            <status>finalizada</status>
            <startTime>2024-10-07T21:07:08.240062500</startTime>
        </ride>
        <ride>
            <rideId>d1307759-906e-4509-9372-dbcda00eb26b</rideId>
            <passengerId>f4a69956-2775-4456-bf33-4656079f83ee</passengerId>
            <cabbieId>3bfbdfac-a916-4611-befd-51384e9e9c1b</cabbieId>
            <vehicleId>2abefd0c-35c8-4b7b-adaf-50030280d5d2</vehicleId>
            <pickupLocation>SHOPPING</pickupLocation>
            <dropLocation>ESTAÇÃODETREM</dropLocation>
            <rideDistance>8.06</rideDistance>
            <status>finalizada</status>
            <startTime>2024-10-07T21:07:08.240062500</startTime>
        </ride>
        <ride>
            <rideId>b509a47d-867e-4b84-b3bc-bf08da2a6583</rideId>
            <passengerId>f4a69956-2775-4456-bf33-4656079f83ee</passengerId>
            <cabbieId>3bfbdfac-a916-4611-befd-51384e9e9c1b</cabbieId>
            <vehicleId>2abefd0c-35c8-4b7b-adaf-50030280d5d2</vehicleId>
            <pickupLocation>PARQUE</pickupLocation>
            <dropLocation>BIBLIOTECA</dropLocation>
            <rideDistance>15.29</rideDistance>
            <status>em corrida</status>
            <startTime>2024-10-07T21:07:10.240483700</startTime>
        </ride>
    </rides>
    <vehicles>
        <vehicle>
            <vehicleId>2abefd0c-35c8-4b7b-adaf-50030280d5d2</vehicleId>
            <registrationNumber>ABD123</registrationNumber>
            <cabbieId>3bfbdfac-a916-4611-befd-51384e9e9c1b</cabbieId>
            <model>Hyundai</model>
            <year>2008</year>
        </vehicle>
    </vehicles>
</database>
